sudo: required

language: go

services:
  - docker

before_script:
   - cd when_srv

after_success: 
   - docker build -t registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER} .
   - docker push registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER}
   