sudo: required

language: go

go:
  - "1.10.x"

services:
  - docker

go_import_path: github.com/fred01/reminderbot/when_srv

script:
   - go build when_srv.go -o when_srv

after_success: 
   - docker build -t registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER} .
   - docker push registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER}
   