sudo: required

language: go

services:
  - docker

#go_import_path: example.org/pkg/foo

before_script:
   - cd when_srv

script:
   - go build when_srv.go -o when_srv

after_success: 
   - docker build -t registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER} .
   - docker push registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER}
   