sudo: required

language: generic


services:
  - docker


script:
   - cd reminderbot/when_srv
   - docker build -t registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER} .
   
after_success: 
   - docker push registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER}
   