sudo: required

language: bash


services:
  - docker


script:
   - ls -l
   - cd when-srv
   - docker build -t registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER} .
   
after_success: 
   - docker push registry.fred.org.ru/when_srv:${TRAVIS_BUILD_NUMBER}
   