// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: when_srv.proto

package srv.when;

public interface WhenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:main.WhenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
